mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.sm9.boot.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 17211377AbCd@
    url: jdbc:mysql://localhost:3306/sm9?useSSL=true&characterEncoding=utf8&serverTimeZone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver